spring.application.name=tickets

spring.datasource.url=jdbc:postgresql://localhost:5432/daniels
spring.datasource.username=daniels
spring.datasource.password=daniels
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
