server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://events-service:8080
              predicates:
                - Path=/auth/**
            - id: registration-service
              uri: http://registration-service:8080
              predicates:
                - Path=/registration/**

            - id: events-service
              uri: http://events-service:8080
              predicates:
                - Path=/events/**